In [2]:
import numpy as np
import gym
from gym import spaces
import json
from collections import defaultdict
import ptan
import os

In [8]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)


cuda


In [6]:
torch.cuda.device_count()

2

In [4]:
class EpistasisEnv(gym.Env):
    
#metadata = {'render.modes': ['human']}
    def __init__(self):
        self.AMOUNT_OF_DATA = 1000
        self.SAMPLE_SIZE = 300 #t1 = t2 = SAMPLE_SIZE
        self.reset()
        
    def establish_phen_gen(self, file):
            with open(file) as f:
                data = json.load(f)
                genotype = np.array(data["genotype"])
                
                self.phenotype = np.array(data["phenotype"])
                self.genotype = genotype.T
                num_phenotypes = max(self.phenotype)+1
                self.disease_snps = data["disease_snps"]
                self.phen_gen = [[] for _ in range(num_phenotypes)]
                for i in range(len(self.genotype)):
                    self.phen_gen[self.phenotype[i]].append(i)  
                return  self.genotype.shape[0], self.genotype.shape[1]    

    
    def step(self, action):
        snp_ids = self._take_action(action)
        # print(f"{snp_ids=}")
        reward = self._count_reward(snp_ids) 
        self.current_step += 1
        done = self.current_step == 1
        obs = self._next_observation()
        return obs, reward, done, {}
    
    def _count_reward(self, snp_ids):
        # print(len(snp_ids))
        # print(len(self.disease_snps))
        
        all_existing_seq = defaultdict(lambda: {'control' : 0, 'case' : 0})
        

        for i, idv in enumerate(self.obs):
            snp_to_cmp = tuple(idv[snp_id] for snp_id in snp_ids) #tuple of SNP that 
            if self.obs_phenotypes[i] == 0:
                all_existing_seq[snp_to_cmp]['control'] += 1
            else:
                all_existing_seq[snp_to_cmp]['case'] += 1

        ###count reward      
        TP = 0 #HR case
        FP = 0 #HR control
        TN = 0 #LR control
        FN = 0 #LR case

        for case_control_count in all_existing_seq.values():
          # if seq is in LR group
            if case_control_count['case'] <= case_control_count['control']: #вопрос <= или <
                FN += case_control_count['case']
                TN += case_control_count['control']
            else:
          # if seq is in HR group
                TP += case_control_count['case']
                FP += case_control_count['control']
        R = (FP + TN) / (TP + FN)
        delta = FP / (TP+0.001)
        gamma = (TP + FP + TN + FN) / (TP+0.001)
        CCR = 0.5 * (TP / (TP + FN) + TN / (FP + TN))
#         print("delta:",delta,"gamma:", gamma)
        U = (R - delta)**2 / ((1 + delta) * (gamma - delta - 1 + 0.001))
        koef = 1
        if len(snp_ids) > len(self.disease_snps):
                print("len(snp_ids) > len(self.disease_snps)")
                koef = 1 / len(snp_ids)

        return koef*(CCR + U)

  
    def reset(self):
        random_sim_idx = np.random.randint(self.AMOUNT_OF_DATA)
        filename = f"./epigen/sim/{random_sim_idx}_1_ASW.json"
        if not os.path.exists(filename):
            os.system(f"cd ./epigen/ && python3 simulate_data.py --sim-ids {random_sim_idx} --corpus-id 1 --pop ASW --inds 5000 --snps 100 --model models/ext_model.ini")

        self.N_IDV, self.N_SNPS = self.establish_phen_gen(filename)
        self.action_space = spaces.Box(low=0, high=1, shape=(self.N_SNPS,), dtype=np.uint8)
        self.observation_space = spaces.Box(low=0, high=2, shape=
                        (2*self.SAMPLE_SIZE, self.N_SNPS), dtype=np.uint8)
        self.obs_phenotypes = None
        self.obs = None
        self.current_step = 0
        self.obs = self._next_observation()
        return self.obs

    def render(self, mode='human', close=False):
        pass
    
    def _take_action(self, action):
        chosen_snp_ids = []
        for i, choice in enumerate(action):
            if choice == 1:
                chosen_snp_ids.append(i)
        return chosen_snp_ids    
    
    def _next_observation(self):
        id_0 = np.random.choice(self.phen_gen[0], self.SAMPLE_SIZE)
        id_1 = np.random.choice(self.phen_gen[1], self.SAMPLE_SIZE)
        sample_ids = np.array(list(zip(id_0,id_1))).flatten()
        self.obs = np.array([self.genotype[idv] for idv in sample_ids])
        self.obs_phenotypes = [self.phenotype[idv] for idv in sample_ids]

        return self.obs

In [5]:
class EpiProbabilityActionSelector(ptan.actions.ActionSelector):
    """
    Converts probabilities of actions into action by sampling them
    """
    def __call__(self, probs):
        assert isinstance(probs, np.ndarray)
        assert isinstance(probs[0], np.ndarray)
        actions = []
#         print("EpiProbabilityActionSelector - probs shape:", probs.shape)
#         for prob in probs:
# #             print("prob", prob.shape)
#             num_selected_snps = 0
#             for oneprob in prob:
#                 if oneprob > 1/len(prob):
#                     num_selected_snps += 1
        for prob in probs:
            num_selected_snps = 2
            # num_selected_snps = 0
            # amount_of_oneprob_more_than_1_div_n = 0
            # while amount_of_oneprob_more_than_1_div_n < 2:
            #     amount_of_oneprob_more_than_1_div_n = 0
            #     if num_selected_snps > len(prob)/10:
            #         num_selected_snps = int(len(prob)/10)
            #         break
            #     num_selected_snps += 1
            #     for oneprob in prob:
            #         if oneprob > 1 / num_selected_snps:
            #             amount_of_oneprob_more_than_1_div_n += 1
            

            chosen_snp = np.random.choice(len(prob), size=num_selected_snps, replace=False, p=prob)
            action = np.zeros(len(prob))
            for snp in chosen_snp:
                action[snp] = 1
            actions.append(action)
        return np.array(actions)

In [4]:
probs = [[0.8, 0.1, 0.1], [0.4, 0.4, 0.2]]
for prob in probs:
            num_selected_snps = sum(1 for oneprob in prob if oneprob > 1/len(prob))
            print(num_selected_snps)
            chosen_snp = np.random.choice(len(prob),size=2, p=prob, replace=False)
            print(chosen_snp)

1
[0 1]
2
[1 0]


In [5]:
import math
import time

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
from torch.nn import Parameter
from torchvision import datasets, transforms

class LinearARD(nn.Module):
    def __init__(self, in_features, out_features, threshold, bias=True):
        super(LinearARD, self).__init__()
        """
            in_features: int, a number of input features
            out_features: int, a number of neurons
            threshold: float, a threshold for clipping weights
        """
        
        self.in_features = in_features
        self.out_features = out_features
        self.threshold = threshold

        self.mu = nn.parameter.Parameter(torch.Tensor(self.out_features, self.in_features)) # torch.nn.parameter.Parameter of size out_features x in_features
        self.log_sigma = nn.parameter.Parameter(torch.Tensor(self.out_features, self.in_features)) # torch.nn.parameter.Parameter of size out_features x in_features
        self.bias = nn.parameter.Parameter(torch.Tensor(1, self.out_features)) # torch.nn.parameter.Parameter of size 1 x out_features
        self.reset_parameters()
        
    def reset_parameters(self):
        self.bias.data.zero_()
        self.mu.data.normal_(0, 0.02)
        self.log_sigma.data.fill_(-5)        
        
    def forward(self, x):      
        # x is a torch.Tensor of shape (number_of_objects, in_features)
        # log_alpha is a torch.Tensor of shape (out_features, in_features)
        self.log_alpha = 2*self.log_sigma-torch.log(self.mu**2+1e-16)# Compute using self.log_sigma and self.mu
        # clipping for a numerical stability
        self.log_alpha = torch.clamp(self.log_alpha, -10, 10)   
        
        if self.training:
            # LRT = local reparametrization trick
            # lrt_mean is a torch.Tensor of shape (x.shape[0], out_features)
            lrt_mean = F.linear(input=x, weight=self.mu, bias=self.bias) # compute mean activation using LRT; you can use F.linear
            # lrt_std is a torch.Tensor of shape (x.shape[0], out_features)
            lrt_std = torch.sqrt(1e-8+F.linear(input=x**2, weight=torch.exp(2*self.log_sigma), bias=None)) # compute std of activations unsig lrt; you can use F.linear
                      # do not forget use torch.sqrt(x + 1e-8) instead of torch.sqrt(x)
            # eps is a torch.Tensor of shape (x.shape[0], out_features)
            eps = torch.randn_like(lrt_std)# sample of noise for reparametrization
            return lrt_mean+lrt_std*eps# sample of activation
        
        # compute the output of the layer
        # use weights W = E q = self.mu
        # clip all weight with log_alpha > threshold
        return F.linear(input=x, weight=self.mu*(self.log_alpha < self.threshold).float(), bias=self.bias)
        
    def kl_reg(self):
        # kl is a scalar torch.Tensor 
        # kl = # eval the KL divergence
        log_alpha = 2*self.log_sigma-torch.log(self.mu**2+1e-16) # Eval log alpha as a function(log_sigma, W)
        log_alpha = torch.clamp(log_alpha, -10, 10)# Clip log alpha to be in [-10, 10] for numerical suability 
        kl = - 0.5 * torch.log1p(torch.exp(-log_alpha))
        KL  = - torch.sum(kl)
        return KL
    
class Net(nn.Module):
    def __init__(self, threshold):
        super(Net, self).__init__()
        self.fc1 = LinearARD(100, 300, threshold)
        self.fc2 = LinearARD(300,  100, threshold)
#         self.fc3 = LinearARD(100,  10, threshold)
        self.threshold=threshold

    def forward(self, x):
        x = F.relu(self.fc1(x))
#         x = F.relu(self.fc2(x))
        x = F.log_softmax(self.fc2(x), dim=1)
        return x    

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class SnpPGN(nn.Module):
    def __init__(self, input_shape, n_actions):
        super(SnpPGN, self).__init__()

        self.conv = nn.Sequential(
            nn.Conv1d(input_shape[0], 32, kernel_size=8, stride=4),
            nn.ReLU(),
            nn.Conv1d(32, 64, kernel_size=4, stride=2),
            nn.ReLU(),
            nn.Conv1d(64, 64, kernel_size=3, stride=1),
            nn.ReLU()
        )

        conv_out_size = self._get_conv_out(input_shape)
        self.fc = nn.Sequential(
            nn.Linear(conv_out_size, 512),
            nn.ReLU(),
            nn.Linear(512, n_actions)
        )

    def _get_conv_out(self, shape):
        o = self.conv(torch.zeros(1, *shape))
        return int(np.prod(o.size()))

    def forward(self, x):
        
#         fx = x.float() / 256
        fx = x.float() / 3
        conv_out = self.conv(fx).view(fx.size()[0], -1)
        return self.fc(conv_out)

In [ ]:
import wandb
import gym
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim



GAMMA = 0.99
LEARNING_RATE = 0.01
EPISODES_TO_TRAIN = 4
COUNT = 1000000
WANDB = True


def calc_qvals(rewards):
    res = []
    sum_r = 0.0
    for r in reversed(rewards):
        sum_r *= GAMMA
        sum_r += r
        res.append(sum_r)
    res = list(reversed(res))
    mean_q = np.mean(res)
    return [q - mean_q for q in res]


if __name__ == "__main__":
    SAMPLE_SIZE = 300 #t1 = t2 = SAMPLE_SIZE
#     filename = "./epigen/sim/0_2_ASW.json"
    env = EpistasisEnv()
    if WANDB:
        wandb.init(project="epistasis", entity="taisikus", config={
          "learning_rate": LEARNING_RATE,
          "gamma": GAMMA,
          "episodes_to_train": EPISODES_TO_TRAIN,
          "steps_number" : COUNT,
          "data_amount": env.AMOUNT_OF_DATA,
        })
        
#     writer = SummaryWriter(comment="-cartpole-reinforce")

#     net = PGN(env.observation_space.shape[1], env.N_SNPS)
    net = SnpPGN(env.observation_space.shape, env.N_SNPS)
    net = nn.DataParallel(net)
    net.to(device)
    print(net)
    agent = ptan.agent.PolicyAgent(net, action_selector=EpiProbabilityActionSelector(),preprocessor=ptan.agent.float32_preprocessor,
                                   apply_softmax=True, device=device)
    # agent = ptan.agent.PolicyAgent(net, action_selector=EpiProbabilityActionSelector(),
    #                                apply_softmax=True, device=device)
    exp_source = ptan.experience.ExperienceSourceFirstLast(env, agent, gamma=GAMMA)

    optimizer = optim.Adam(net.parameters(), lr=LEARNING_RATE)

    total_rewards = []
    step_idx = 0
    done_episodes = 0

    batch_episodes = 0
    batch_states, batch_actions, batch_qvals = [], [], []
    cur_states, cur_actions, cur_rewards = [], [], []

    for step_idx, exp in enumerate(exp_source):
        cur_states.append(exp.state)
        cur_actions.append(exp.action)
        cur_rewards.append(exp.reward)
        if exp.last_state is None:
            batch_states.extend(cur_states)
            batch_actions.extend(cur_actions)
            batch_qvals.extend(calc_qvals(cur_rewards))
            cur_states.clear()
            cur_actions.clear()
            cur_rewards.clear()
            batch_episodes += 1

        # handle new rewards
        new_rewards = exp_source.pop_total_rewards()
        if new_rewards:
            done_episodes += 1
            reward = new_rewards[0]
            total_rewards.append(reward)
            mean_rewards = float(np.mean(total_rewards[-100:]))

            # print("%d: reward: %6.2f, mean_100: %6.2f, episodes: %d" % (
            #     step_idx, reward, mean_rewards, done_episodes))
            if WANDB:
                wandb.log({"reward": reward, "mean_100": mean_rewards})
#        
            if mean_rewards > 0.96:
                print("Solved in %d steps and %d episodes!" % (step_idx, done_episodes))
                break
            if done_episodes > COUNT:
                print(f"done_episodes > {COUNT}")
                break

        if batch_episodes < EPISODES_TO_TRAIN:
            continue

        optimizer.zero_grad()
        states_v = torch.FloatTensor(batch_states)
        states_v = states_v.to(device)
        batch_actions_t = torch.FloatTensor(batch_actions)
        batch_actions_t = batch_actions_t.to(device)
        batch_qvals_v = torch.FloatTensor(batch_qvals)
        batch_qvals_v = batch_qvals_v.to(device)

        logits_v = net(states_v)
        log_prob_v = F.log_softmax(logits_v, dim=1)
#         print(log_prob_v.shape)
#         print(batch_qvals_v.shape)
#         print(len(batch_states))
#         print(batch_actions_t.shape)
#         log_prob_actions_v = batch_qvals_v * log_prob_v[range(len(batch_states)), batch_actions_t]
        log_prob_actions_v = batch_qvals_v * torch.diagonal(torch.mm(log_prob_v, torch.transpose(batch_actions_t, 0, 1)))
        loss_v = -log_prob_actions_v.mean()

        loss_v.backward()
        optimizer.step()

        batch_episodes = 0
        batch_states.clear()
        batch_actions.clear()
        batch_qvals.clear()
    if WANDB:
        wandb.finish()


############################################################################
######################### EpiGEN - simulate_data.py ########################

Loading genotype corpus.
Genotype corpus contains 116415 SNPs and 10000 individuals.
Loading SNPs.
Loading MAFs.
Loading cumulative MAF distribution.
Parsing epistasis model.
Checking input consistency.
----------------------------------------------------------------------------
Starting simulation for simulation ID 686.
Checking disease MAF range (extend if too narrow).
Checking noise MAF range (extend if too narrow).
Sampling disease SNPs.
Sampling noise SNPs.
Updating genotype matrix, MAF array, and SNP list.
Generating the phenotypes.
Subsampling the individuals.
Serializing the simulated data.
----------------------------------------------------------------------------
Finished simulation of epistasis data.
The generated data can be found in the ./sim directory:
Generated data:	./sim/686_1_ASW.json

############################

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: taisikus (use `wandb login --relogin` to force relogin)
/home/tskhakharova/.local/lib/python3.9/site-packages/wandb/sdk/lib/ipython.py:47: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML  # type: ignore


SnpPGN(
  (conv): Sequential(
    (0): Conv1d(600, 32, kernel_size=(8,), stride=(4,))
    (1): ReLU()
    (2): Conv1d(32, 64, kernel_size=(4,), stride=(2,))
    (3): ReLU()
    (4): Conv1d(64, 64, kernel_size=(3,), stride=(1,))
    (5): ReLU()
  )
  (fc): Sequential(
    (0): Linear(in_features=576, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=100, bias=True)
  )
)

############################################################################
######################### EpiGEN - simulate_data.py ########################

Loading genotype corpus.
Genotype corpus contains 116415 SNPs and 10000 individuals.
Loading SNPs.
Loading MAFs.
Loading cumulative MAF distribution.
Parsing epistasis model.
Checking input consistency.
----------------------------------------------------------------------------
Starting simulation for simulation ID 763.
Checking disease MAF range (extend if too narrow).
Checking noise MAF range (extend if too narrow).
Samplin

/tmp/job-758062/ipykernel_248584/71870525.py:118: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646756402876/work/torch/csrc/utils/tensor_new.cpp:210.)
  states_v = torch.FloatTensor(batch_states)



############################################################################
######################### EpiGEN - simulate_data.py ########################

Loading genotype corpus.
Genotype corpus contains 116415 SNPs and 10000 individuals.
Loading SNPs.
Loading MAFs.
Loading cumulative MAF distribution.
Parsing epistasis model.
Checking input consistency.
----------------------------------------------------------------------------
Starting simulation for simulation ID 817.
Checking disease MAF range (extend if too narrow).
Checking noise MAF range (extend if too narrow).
Sampling disease SNPs.
Sampling noise SNPs.
Updating genotype matrix, MAF array, and SNP list.
Generating the phenotypes.
Subsampling the individuals.
Serializing the simulated data.
----------------------------------------------------------------------------
Finished simulation of epistasis data.
The generated data can be found in the ./sim directory:
Generated data:	./sim/817_1_ASW.json

############################

In [2]:
env = EpistasisEnv()
print(env.observation_space)
env.observation_space.shape

Box(0, 2, (600, 100), uint8)


(600, 100)

In [ ]:
env.reset()
observation, reward, done, _ = env.step(env.action_space.sample())
print('Observation : ' + str(observation.shape))
print('Reward      : ' + str(reward))
print('Done        : ' + str(done))

## Создали среду и запустили

In [23]:
env = EpistasisEnv()
env.reset()

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 1, 1, ..., 2, 0, 0],
       [0, 0, 2, ..., 2, 0, 0],
       [0, 1, 0, ..., 2, 0, 0]])

In [24]:
env.action_space.sample()

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1], dtype=uint8)

In [25]:
probs = np.random.random(size=100)
probs /= probs.sum()

In [26]:
action_selector = EpiProbabilityActionSelector()
probs = np.array([probs])

action = action_selector(probs)
print(action.shape, action)

EpiProbabilityActionSelector - probs shape: (1, 100)
(1, 100) [[0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1.
  1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1.
  1. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1.
  1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.
  0. 0. 0. 0.]]


In [27]:
env.step(env.action_space.sample())

snp_ids=[0, 3, 4, 5, 8, 11, 12, 15, 16, 19, 21, 22, 27, 28, 29, 32, 34, 35, 37, 39, 40, 42, 43, 45, 47, 48, 50, 52, 53, 54, 57, 60, 61, 64, 68, 74, 76, 78, 79, 84, 86, 87, 89, 92, 96, 99]


(array([[0, 0, 1, ..., 1, 0, 0],
        [0, 0, 2, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 1, ..., 1, 0, 0],
        [0, 0, 2, ..., 1, 0, 0],
        [0, 1, 1, ..., 1, 0, 0]]),
 1.9990076523764393,
 True,
 {})

In [11]:
env = gym.make("CartPole-v0")
print(env.observation_space)
env.observation_space.shape

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)


(4,)

In [ ]:
env = gym.make('CartPole-v0')
env.reset()
for i in range(500):
   observation, reward, done, _ = env.step(env.action_space.sample())
   print('Observation : ' + str(observation.shape))
   print('Reward      : ' + str(reward))
   print('Done        : ' + str(done))
   if done:
        print(observation)
   print('---------------------')
env.close()

In [ ]:
[5,2]

In [14]:
a = torch.tensor([[0.2,0.3,0.4],[0.5,0.7,0.8],[0.1,0.1,0.1], [0.2,0.2,0.2]], dtype=torch.float64)
b = torch.tensor([[0,0,1],[1,0,0],[1,0,1],[0,1,1]], dtype=torch.float64)
c = torch.diagonal(torch.mm(a, torch.transpose(b, 0, 1)))

In [15]:
c

tensor([0.4000, 0.5000, 0.2000, 0.4000], dtype=torch.float64)

In [18]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
c = a*b
print(c)

tensor([ 4, 10, 18])


In [13]:
prob = torch.softmax(torch.rand(10), 0)
print(prob)

num_selected_snps = 0
amount_of_oneprob_more_than_1_div_n = 0
while amount_of_oneprob_more_than_1_div_n <= 1:
    if num_selected_snps > len(prob):
        break
    amount_of_oneprob_more_than_1_div_n = 0
    num_selected_snps += 1
    for oneprob in prob:
        if oneprob > 1 / num_selected_snps:
            amount_of_oneprob_more_than_1_div_n += 1
    print("amount_of_oneprob_more_than_1_div_n", amount_of_oneprob_more_than_1_div_n )
    print("num_selected_snps", num_selected_snps)

tensor([0.0966, 0.0629, 0.1407, 0.1090, 0.1407, 0.1056, 0.1225, 0.0878, 0.0622,
        0.0719])
amount_of_oneprob_more_than_1_div_n 0
num_selected_snps 1
amount_of_oneprob_more_than_1_div_n 0
num_selected_snps 2
amount_of_oneprob_more_than_1_div_n 0
num_selected_snps 3
amount_of_oneprob_more_than_1_div_n 0
num_selected_snps 4
amount_of_oneprob_more_than_1_div_n 0
num_selected_snps 5
amount_of_oneprob_more_than_1_div_n 0
num_selected_snps 6
amount_of_oneprob_more_than_1_div_n 0
num_selected_snps 7
amount_of_oneprob_more_than_1_div_n 2
num_selected_snps 8


In [14]:
m = nn.LogSoftmax()
input = torch.randn(2, 3)
output = m(input)
print(output)

tensor([[-0.3254, -3.1408, -1.4503],
        [-1.5679, -0.9382, -0.9159]])


/tmp/job-730799/ipykernel_198874/3113266456.py:3: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  output = m(input)
